test = {   'name': 'q5_6_7',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> "gdp_pc" in list(my_countries.columns)\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> np.isclose(my_countries[(my_countries[\'country\'] == "Singapore") & (my_countries[\'year\'] == 1960)][\'gdp_pc\'].values[0], 9284.94520345)\nTrue',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
